# Site settings
title: MEI Guidelines
email: info@music-encoding.org
baseurl: "/guidelines" 
url: "https://music-encoding.org/guidelines"
style_baseurl: "https://music-encoding.github.io"
#style_baseurl: "http://localhost:4001"
twitter_username: music-encoding
github: [metadata]


# Github repository used for Github edit button.
repository: "music-encoding/guidelines"

# path fragment to get to branch for files on github:
github_edit_path: "blob/master"

# Build settings
markdown: kramdown

exclude: [tools]

plugins:
  - jekyll-redirect-from
  
menu:
    - id: versions
      label: 'Guidelines versions'
      url: ''
      submenu:
          #- id: dev
            #url: 'dev'
          - id: v4
            url: 'v4'
          - id: v3
            url: 'v3'

versions:
    current: "v4"
    editable: "v4"
    # names
    dev: "development version"
    v3: "3.0.0"
    v4: "4.0.1"

collections:
  #guidelines-dev:
    #output: false
  guidelines-v4:
    output: false
  guidelines-v3:
    output: false

sidebar:  
    - id: s1
      content: 
          - id: guidelines
            label: 'Guidelines'
            url: 'content/'
          - id: elements
            label: 'Elements'
            url: 'elements.html'
          - id: attributeclasses
            label: 'Attribute Classes'
            url: 'attribute-classes.html'
          - id: modelclasses
            label: 'Model Classes'
            url: 'model-classes.html'
          - id: datatypes
            label: 'Data Types'
            url: 'data-types.html'
          - id: datatypes
            label: 'Macro Groups'
            url: 'macro-groups.html'
